// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umklnmktfazfqmtzhitv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVta2xubWt0ZmF6ZnFtdHpoaXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTM5NzQsImV4cCI6MjA3MTUyOTk3NH0.ZWBbygYO_aBCA4zq1V14V8f5_yE4Pz30Z89q525F2MQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});